In [43]:
#importing the lib and reading data

In [44]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib as mpl
%matplotlib inline
mpl.style.use('ggplot')

In [45]:
cars=pd.read_csv('quikr_car.csv')

In [46]:
#exploring the dataset characteristics

In [47]:
car.head()


name   company  year    Price  kms_driven fuel_type
0  Mahindra XUV500 W6  Mahindra  2014  8500003       45000    Diesel
1   Audi A3 Cabriolet      Audi  2015  3100000       12516    Petrol

In [48]:
car.tail()

name   company  year    Price  kms_driven fuel_type
0  Mahindra XUV500 W6  Mahindra  2014  8500003       45000    Diesel
1   Audi A3 Cabriolet      Audi  2015  3100000       12516    Petrol

In [49]:
car.shape

(2, 6)

In [50]:
car.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   name        2 non-null      object
 1   company     2 non-null      object
 2   year        2 non-null      int32 
 3   Price       2 non-null      int32 
 4   kms_driven  2 non-null      int32 
 5   fuel_type   2 non-null      object
dtypes: int32(3), object(3)
memory usage: 204.0+ bytes


In [51]:
# we noticed that all the data in the csv is of object type and hence we need to fix it lets now exploring each solumn to find any other anomalies

In [52]:
car['Price'].unique()


array([8500003, 3100000])

In [53]:
# we can see that the price is in object which neededs to be converted in the later stages and there ar some values which are string(eg:'ask for price')

In [54]:
car['year'].unique()

array([2014, 2015])

In [55]:
# we can see that the year is filled with values which are non year values  (eg:'able,) and we need to remove them and change the value from obj to int format

In [56]:
car['kms_driven'].unique()

array([45000, 12516])

In [57]:
#as we can see there are kms joined with the kilometers which will be needed to be removed  and it will be then required to be converted into an int type

In [58]:
car['fuel_type'].unique()

array(['Diesel', 'Petrol'], dtype=object)

In [59]:
# as we see there are certain nan values which will be needed to remove

In [60]:
# cleaning/Treating the data

In [61]:
# making an backup of the data
b_car=car.copy()

In [62]:
#handeling/removing non numerical values from the colums of year and converting them to int
#car['year'].str.isnumeric()
car=car[car['year'].str.isnumeric()]
car['year']=car['year'].astype(int)

AttributeError: Can only use .str accessor with string values!

In [63]:
#removing the anomalies such as entire strings of words,"," and then changing the data ty
car=car[car['Price']!='Ask For Price']
#car['Price'].str.replace(',','')
car['Price']=car['Price'].str.replace(',','').astype(int)


AttributeError: Can only use .str accessor with string values!

In [ ]:
# removing the strings and comas and kms and converting it to an int type
car['kms_driven']=car['kms_driven'].str.split().str.get(0).str.replace(',','')
car=car[car['kms_driven'].str.isnumeric()]
car['kms_driven']=car['kms_driven'].astype(int)

In [ ]:
# removing na values from fuel_type column
car=car[~car['fuel_type'].isna()]

In [ ]:
#removing  and keeping the only first three words of the car name
car['name']=car['name'].str.split().str.slice(start=0,stop=3).str.join(' ')

In [ ]:
# after cleaning the data some index where removed hence reseting the index
car=car.reset_index(drop=True)

In [ ]:
car.describe()

In [ ]:
# as we can see the price of 75% of cars is below 5laks but the maximum value is 85 laks hence it is an outlier and needs to be treated 
#car=car[car['Price']>3000000].reset_index(drop=True)

In [ ]:
car
